[functions.admin-create-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-reset-all-passwords]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.process-magic-link-queue]
verify_jwt = false

# [cron]
# jobs = [
#   { name = "process-magic-link-queue", schedule = "* * * * *", command = "process-magic-link-queue" }
# ]

